### ISSUE TITLE
ORGANIZATION is always required

### ISSUE THREAD

**Issue by timdittler** [github/cleanowners#27]
Contrary to the README, the env var ORGANIZATION is always required. Otherwise the action will fail with
```
Traceback (most recent call last):
  File "/action/workspace/cleanowners.py", line 206, in <module>
    main()
  File "/action/workspace/cleanowners.py", line [8](https://github.com/Staffbase/infrastructure/actions/runs/8158526447/job/22300640673?pr=5510#step:4:9)[9](https://github.com/Staffbase/infrastructure/actions/runs/8158526447/job/22300640673?pr=5510#step:4:10), in main
    if not github_connection.organization(organization).is_member(username):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.[12](https://github.com/Staffbase/infrastructure/actions/runs/8158526447/job/22300640673?pr=5510#step:4:13)/site-packages/github3/github.py", line 1688, in organization
    json = self._json(self._get(url), 200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/github3/models.py", line [16](https://github.com/Staffbase/infrastructure/actions/runs/8158526447/job/22300640673?pr=5510#step:4:17)1, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found

**Comment by jmeridth** [comment]
@timdittler you cool if I get a PR up for this? or were you planning to go after it?

**Comment by timdittler** [comment]
@jmeridth Of course. I would be happy if you fixed it!

**Comment by jmeridth** [comment]
@timdittler reading the code more, I believe we currnetly don't want to make `ORGANIZATION` required.  As the README currently reads, a user can provide a `REPOSITORY` environment variable instead of `ORGANIZATION` that includes specific repositories, from potentially multiple organizations. Currently at least one of them is required.

What I'm thinking:

If `ORGANIZATION` environment variable is provided:

- focus on that single organization's repositories

if `REPOSITORY` environment variable list is provided:

- verify that each org prefix on the repositories is an actual org
- use that org as the `organization` variable in [this line of code](https://github.com/github/cleanowners/blob/fa9994a350a5831b50173f704e2016f484bc0d68/cleanowners.py#L89) (the one causing the error in this issue)

**note:** currently, if both environment variables are used, `ORGANIZATION` has priority and `REPOSITORY` is ignored. (future, allow both and parse accordingly)

Gonna try out a PR.
